{% set python_min = '3.10' %}
{% set name = "ctlearn" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}
  
source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ctlearn-{{ version }}.tar.gz
  sha256: 1e0429e0ae20e35adeed9445d482944064798a8e1962bc97d77c520256672c39
  
build:
  entry_points:
    - ctlearn = ctlearn.run_model:main
    - build_irf = ctlearn.build_irf:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=65
    - setuptools-scm >=6.2
    - pip
  run:
    - python >={{ python_min }}
    - dl1_data_handler >=0.12.0
    - tensorflow >=2.15.0,<2.16.0
    - astropy
    - matplotlib-base
    - numpy
    - pandas
    - pip
    - pyyaml
    - scikit-learn
    - ctaplot
    - numba >=0.56.2,<0.57
    - pydot
    - pyirf
    
test:
  imports:
    - ctlearn
  commands:
    - pip check
    - ctlearn --help
    - build_irf --help
  requires:
    - pip
    - python {{ python_min }}
    
about:
  home: https://github.com/ctlearn-project/ctlearn
  summary: CTLearn is a package under active development to run deep learning models to analyze data from all major current and future arrays of imaging atmospheric Cherenkov telescopes (IACTs).
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rcervinoucm
